// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZjW4TQAMEEnWps8n2RgXxP9qCup3X8A',
    appId: '1:596958782600:android:5beaba60bdd12b25c7eb3d',
    messagingSenderId: '596958782600',
    projectId: 'attendance-system-32e95',
    storageBucket: 'attendance-system-32e95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSkoJsGP4HOUw1xKHkidC3bebG0FAoYss',
    appId: '1:596958782600:ios:315d62f87a584614c7eb3d',
    messagingSenderId: '596958782600',
    projectId: 'attendance-system-32e95',
    storageBucket: 'attendance-system-32e95.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSkoJsGP4HOUw1xKHkidC3bebG0FAoYss',
    appId: '1:596958782600:ios:315d62f87a584614c7eb3d',
    messagingSenderId: '596958782600',
    projectId: 'attendance-system-32e95',
    storageBucket: 'attendance-system-32e95.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2C8daP_PdEVclxceJq-yZA5b7UWApTuQ',
    appId: '1:596958782600:web:f7bf8efef062f829c7eb3d',
    messagingSenderId: '596958782600',
    projectId: 'attendance-system-32e95',
    authDomain: 'attendance-system-32e95.firebaseapp.com',
    storageBucket: 'attendance-system-32e95.firebasestorage.app',
    measurementId: 'G-5CM4LQ72T9',
  );

}